import { StyleSheet } from 'react-native';

import { tokens } from '@/shared/theme/tokens';

export const guestNavigationStyles = StyleSheet.create({
  rootHeaderSafeArea: {
    backgroundColor: tokens.color.surface,
  },
  rootHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: tokens.layout.screenInset,
    paddingVertical: tokens.space.sm,
  },
  rootHeaderTitle: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.title,
    fontWeight: '600',
  },
  childBackButton: {
    alignItems: 'center',
    height: tokens.layout.controlHeight,
    justifyContent: 'center',
    width: tokens.layout.controlHeight,
  },
  childHeaderActions: { alignItems: 'center', flexDirection: 'row', gap: tokens.space.xs, minWidth: tokens.layout.controlHeight },
  childBackArrow: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.title + tokens.space.xs / 2,
  },
  childHeaderTitle: {
    color: tokens.color.inkStrong,
    flex: 1,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.title,
    fontWeight: '600',
    marginLeft: tokens.space.xs,
  },
  childHeaderEndSpacer: {
    height: tokens.layout.controlHeight,
    width: tokens.layout.controlHeight,
  },
  menuButton: {
    alignItems: 'center',
    backgroundColor: tokens.color.white,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.control,
    borderWidth: 1,
    height: tokens.layout.controlHeight,
    justifyContent: 'center',
    width: tokens.layout.controlHeight,
  },
  menuButtonLabel: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.sectionTitle,
  },
  shell: {
    backgroundColor: tokens.color.white,
    borderColor: tokens.color.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: tokens.space.md,
    height: tokens.layout.guestNavigationHeight,
    paddingHorizontal: tokens.space.guestNavigationInset,
    paddingVertical: tokens.space.sm,
  },
  tab: {
    alignItems: 'center',
    flex: 1,
    height: tokens.layout.guestNavigationTabHeight,
    gap: tokens.space.xs / 2,
    justifyContent: 'center',
    paddingHorizontal: tokens.space.xs,
    paddingVertical: tokens.space.xs,
  },
  tabActive: {
    backgroundColor: tokens.color.surfaceAccent,
    borderRadius: tokens.radius.guestNavigationTab,
  },
  tabPressed: {
    opacity: 0.72,
  },
  tabLabel: {
    color: tokens.color.muted,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.caption,
    fontWeight: '500',
  },
  tabLabelActive: {
    color: tokens.color.brand,
    fontWeight: '600',
  },
  chatFab: {
    alignItems: 'center',
    backgroundColor: tokens.color.brand,
    borderRadius: tokens.layout.controlHeight / 2,
    bottom: tokens.layout.guestNavigationHeight + tokens.space.md,
    height: tokens.layout.controlHeight,
    justifyContent: 'center',
    position: 'absolute',
    right: tokens.layout.screenInset,
    width: tokens.layout.controlHeight,
    zIndex: 2,
  },
  chatFabIcon: {
    height: tokens.layout.controlHeight / 2,
    width: tokens.layout.controlHeight / 2,
  },
  drawerModal: {
    bottom: 0,
    flex: 1,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 4,
  },
  drawerBackdrop: {
    backgroundColor: tokens.color.black,
    flex: 1,
    opacity: 0.48,
  },
  drawerBackdropFill: {
    flex: 1,
  },
  drawer: {
    backgroundColor: tokens.color.surface,
    borderBottomLeftRadius: tokens.radius.card,
    borderColor: tokens.color.border,
    borderLeftWidth: 1,
    borderTopLeftRadius: tokens.radius.card,
    bottom: 0,
    elevation: 4,
    flex: 1,
    maxWidth: 420,
    paddingHorizontal: tokens.layout.screenInset,
    paddingTop: tokens.space.md,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '88%',
  },
  drawerHeader: {
    alignItems: 'center',
    flexShrink: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: tokens.space.xl,
  },
  drawerHeaderCopy: {
    gap: tokens.space.xs,
  },
  drawerTitle: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.title,
    fontWeight: '600',
  },
  drawerSubtitle: {
    color: tokens.color.muted,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.bodyMedium,
  },
  drawerCloseButton: {
    alignItems: 'center',
    borderRadius: tokens.radius.control,
    height: tokens.layout.controlHeight,
    justifyContent: 'center',
    width: tokens.layout.controlHeight,
  },
  drawerBody: {
    flex: 1,
    minHeight: 0,
  },
  drawerSections: {
    gap: tokens.space.lg,
    paddingBottom: tokens.space.md,
  },
  drawerLogoutArea: {
    borderTopColor: tokens.color.border,
    borderTopWidth: 1,
    flexShrink: 0,
    paddingTop: tokens.space.md,
  },
  drawerLogout: {
    alignItems: 'center',
    borderRadius: tokens.radius.control,
    flexDirection: 'row',
    gap: tokens.space.sm,
    minHeight: tokens.layout.controlHeight,
    paddingHorizontal: tokens.space.sm,
  },
  drawerLogoutLabel: {
    color: tokens.color.destructive,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    fontWeight: '600',
  },
  drawerSection: {
    gap: tokens.space.xs,
  },
  drawerSectionButton: { alignItems: 'center', flexDirection: 'row', gap: tokens.space.xs, minHeight: tokens.layout.controlHeight, paddingHorizontal: tokens.space.xs },
  drawerSectionTitle: {
    color: tokens.color.muted,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.caption,
    fontWeight: '600',
    letterSpacing: 0.6,
    paddingHorizontal: tokens.space.xs,
  },
  drawerLink: {
    alignItems: 'center',
    borderRadius: tokens.radius.control,
    flexDirection: 'row',
    gap: tokens.space.sm,
    minHeight: tokens.layout.controlHeight,
    paddingHorizontal: tokens.space.sm,
  },
  drawerLinkActive: {
    backgroundColor: tokens.color.surfaceAccent,
  },
  drawerItemPressed: {
    opacity: 0.72,
  },
  drawerLinkLabel: {
    color: tokens.color.ink,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    fontWeight: '500',
  },
  drawerLinkLabelActive: {
    color: tokens.color.brand,
    fontWeight: '600',
  },

});
