import { StyleSheet } from 'react-native';

import { tokens } from '@/shared/theme/tokens';

export const roomServiceStyles = StyleSheet.create({
  screen: { backgroundColor: tokens.color.surface, flex: 1 },
  headerButton: { alignItems: 'center', height: tokens.layout.controlHeight + tokens.space.xs, justifyContent: 'center', width: tokens.layout.controlHeight + tokens.space.xs },
  headerButtonDisabled: { opacity: 0.5 },
  contextRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  cartAction: { alignItems: 'center', backgroundColor: tokens.color.surfaceAccent, borderRadius: tokens.radius.control, flexDirection: 'row', gap: tokens.space.xs, justifyContent: 'center', minHeight: tokens.layout.controlHeight, paddingHorizontal: tokens.space.sm },
  cartActionLabel: { color: tokens.color.brand, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label, fontWeight: '600' },
  cartIcon: { fontSize: tokens.typography.size.sectionTitle },
  scroll: { flex: 1 },
  content: { gap: tokens.space.md, padding: tokens.layout.screenInset, paddingBottom: tokens.space.xxl },
  room: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label },
  sectionTitle: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.sectionTitle, fontWeight: '600' },
  categoryList: { flexDirection: 'row', flexWrap: 'wrap', gap: tokens.space.xs },
  categoryOptions: { gap: tokens.space.sm, paddingVertical: tokens.space.sm },
  categoryButton: { backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderRadius: tokens.radius.chip, borderWidth: 1, justifyContent: 'center', minHeight: tokens.layout.buttonHeight, paddingHorizontal: tokens.space.md, paddingVertical: tokens.space.sm },
  categoryButtonSelected: { backgroundColor: tokens.color.surfaceAccent, borderColor: tokens.color.brand },
  categoryLabel: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium, fontWeight: '600' },
  catalog: { gap: tokens.space.sm },
  productCard: { backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderRadius: tokens.radius.card, borderWidth: 1, gap: tokens.space.sm, padding: tokens.space.md },
  productName: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label, fontWeight: '600' },
  productPrice: { color: tokens.color.ink, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label },
  productAction: { alignItems: 'center', backgroundColor: tokens.color.brand, borderRadius: tokens.radius.control, justifyContent: 'center', minHeight: tokens.layout.buttonHeight, paddingHorizontal: tokens.space.md },
  productActionLabel: { color: tokens.color.white, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label, fontWeight: '600' },
  stepper: { alignItems: 'center', flexDirection: 'row', gap: tokens.space.sm },
  stepperButton: { alignItems: 'center', borderColor: tokens.color.brand, borderRadius: tokens.radius.control, borderWidth: 1, height: tokens.layout.buttonHeight, justifyContent: 'center', width: tokens.layout.buttonHeight },
  stepperLabel: { color: tokens.color.brand, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.sectionTitle, fontWeight: '600' },
  quantity: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label, minWidth: tokens.space.xl, textAlign: 'center' },
  modalBackdrop: { backgroundColor: 'rgba(0, 0, 0, 0.35)', flex: 1, justifyContent: 'flex-end' },
  modalSafeArea: { maxHeight: '92%' },
  cartSheet: { backgroundColor: tokens.color.surface, borderTopLeftRadius: tokens.radius.card, borderTopRightRadius: tokens.radius.card, maxHeight: '100%', padding: tokens.layout.screenInset },
  cartHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  cartTitle: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.sectionTitle, fontWeight: '600' },
  closeButton: { alignItems: 'center', height: tokens.layout.buttonHeight, justifyContent: 'center', width: tokens.layout.buttonHeight },
  closeLabel: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.title },
  cartContent: { gap: tokens.space.md, paddingBottom: tokens.space.md, paddingTop: tokens.space.md },
  cartLine: { borderBottomColor: tokens.color.border, borderBottomWidth: 1, gap: tokens.space.sm, paddingBottom: tokens.space.md },
  cartLineInfo: { gap: tokens.space.xs },
  removeButton: { alignSelf: 'flex-start', minHeight: tokens.layout.buttonHeight, justifyContent: 'center', paddingHorizontal: tokens.space.sm },
  removeLabel: { color: tokens.color.brand, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium, fontWeight: '600' },
  emptyCart: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium },
  totalSection: { backgroundColor: tokens.color.surfaceMuted, borderRadius: tokens.radius.card, gap: tokens.space.xs, padding: tokens.space.md },
  total: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.sectionTitle, fontWeight: '600' },
  notes: { backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderRadius: tokens.radius.control, borderWidth: 1, color: tokens.color.ink, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label, minHeight: tokens.layout.controlHeight * 2, padding: tokens.space.md, textAlignVertical: 'top' },
  deliveryPicker: { alignItems: 'center', backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderRadius: tokens.radius.control, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: tokens.layout.buttonHeight, paddingHorizontal: tokens.space.md },
  catalogControls: { alignItems: 'stretch', flexDirection: 'row', gap: tokens.space.sm },
  catalogSearch: { backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderRadius: tokens.radius.control, borderWidth: 1, color: tokens.color.ink, flex: 1.6, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label, height: tokens.layout.buttonHeight, paddingHorizontal: tokens.space.md },
  categorySelector: { alignItems: 'center', backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderRadius: tokens.radius.control, borderWidth: 1, flex: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: tokens.layout.buttonHeight, paddingHorizontal: tokens.space.sm },
  deliveryLabel: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.caption, fontWeight: '600' },
  deliveryValue: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label },
  deliveryPlaceholder: { color: tokens.color.muted },
  deliveryChevron: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.sectionTitle },
  button: { alignItems: 'center', backgroundColor: tokens.color.brand, borderRadius: tokens.radius.control, height: tokens.layout.buttonHeight, justifyContent: 'center', paddingHorizontal: tokens.space.md },
  buttonDisabled: { backgroundColor: tokens.color.brandSoft },
  editItems: { alignItems: 'center', minHeight: tokens.layout.buttonHeight, justifyContent: 'center' },
  editItemsLabel: { color: tokens.color.brand, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label, fontWeight: '600' },
  buttonLabel: { color: tokens.color.white, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label, fontWeight: '600' },
  stateCard: { backgroundColor: tokens.color.surfaceMuted, borderColor: tokens.color.border, borderRadius: tokens.radius.card, borderWidth: 1, gap: tokens.space.sm, padding: tokens.space.lg },
  offlineStateCard: { backgroundColor: tokens.color.pendingSurface },
  successStateCard: { backgroundColor: tokens.color.surfaceAccent, borderColor: tokens.color.brand },
  stateTitle: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.sectionTitle, fontWeight: '600' },
  stateBody: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium },
  skeleton: { backgroundColor: tokens.color.border, borderRadius: tokens.radius.control, height: tokens.layout.controlHeight },
});
