/** Isolated synthetic hosted fields: no network, storage or sensitive values sent to React. */
export const demoCardDocument = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-pms-synthetic-fields'; style-src 'unsafe-inline'; connect-src 'none'; form-action 'none'; base-uri 'none'">
<style>
*{box-sizing:border-box}body{margin:0;padding:4px;color:#344638;font:13px Arial,sans-serif}form{display:grid;gap:20px}label{display:block;font-size:12px;font-weight:600;margin-bottom:8px}input{width:100%;min-width:0;height:48px;padding:12px;border:1px solid #dce2d7;border-radius:10px;background:white;color:#344638;font:inherit}input:focus{outline:2px solid #6b7c62;outline-offset:2px}input[data-valid=true]{border-color:#5a6b5d}input[aria-invalid=true]{border:2px solid #dc2626;background:#fff8f8}input[aria-invalid=true]:focus{outline-color:#fecaca}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.brands{display:flex;gap:8px;margin-top:10px}.brands span{padding:6px 9px;background:#e7ebe4;border:1px solid transparent;border-radius:6px;color:#747d70;font-size:10px;font-weight:bold;transition:background .2s}.brands span.active{color:#344e38;background:white;border-color:#5a6b5d}small{display:block;color:#6c7768;font-size:11px;line-height:1.8;margin-top:8px}button{width:100%;min-height:48px;padding:12px;background:#5a6b5d;color:white;border:0;border-radius:12px;font:inherit;font-weight:600;cursor:pointer;transition:background .2s}button:hover{background:#4a584c}button:focus-visible{outline:2px solid #344638;outline-offset:3px}.field-error{color:#b91c1c;font-size:12px;line-height:1.8;margin:7px 0 0}.field-error:empty{display:none}#error{margin:0;color:#b91c1c;line-height:1.8}#error:empty{display:none}@media(max-width:350px){.grid{gap:12px}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}
</style></head><body>
<form novalidate aria-label="Tarjeta de prueba aislada">
<div><label for="number">Número de tarjeta de prueba</label><input id="number" inputmode="numeric" maxlength="19" autocomplete="off" placeholder="4242 4242 4242 4242" aria-describedby="samples number-error" aria-invalid="false"><div class="brands" aria-label="Marcas de tarjeta"><span id="Visa">VISA</span><span id="Mastercard">Mastercard</span><span id="Amex">AMEX</span></div><p id="number-error" class="field-error" aria-live="polite"></p><small id="samples">Solo números ficticios: Visa 4242 4242 4242 4242 · Mastercard 5555 5555 5555 4444 · Amex 3782 822463 10005 (15 dígitos). Nunca ingreses una tarjeta real.</small></div>
<div class="grid"><div><label for="expiry">Fecha de expiración</label><input id="expiry" inputmode="numeric" maxlength="7" autocomplete="off" placeholder="MM / YY" aria-describedby="expiry-error" aria-invalid="false"><p id="expiry-error" class="field-error" aria-live="polite"></p></div><div><label for="code">CVC / CVV de prueba</label><input id="code" type="password" inputmode="numeric" maxlength="3" autocomplete="off" placeholder="123" aria-describedby="code-help code-error" aria-invalid="false"><p id="code-error" class="field-error" aria-live="polite"></p><small id="code-help">Ejemplo: 123; Amex: 1234. Código del reverso (Amex: anverso).</small></div></div>
<div><label for="holder">Nombre del titular</label><input id="holder" maxlength="250" autocomplete="off" aria-describedby="holder-error" aria-invalid="false"><p id="holder-error" class="field-error" aria-live="polite"></p></div>
<p id="error" role="alert"></p><button type="submit">Usar tarjeta de prueba</button></form>
<script nonce="pms-synthetic-fields">(function(){
var channel='',touched={},errors={};
var form=document.querySelector('form'),number=document.getElementById('number'),expiry=document.getElementById('expiry'),code=document.getElementById('code'),holder=document.getElementById('holder'),summary=document.getElementById('error');
var fields=[number,expiry,code,holder],cards={'4242424242424242':['demo_visa_approved','Visa','4242'],'5555555555554444':['demo_mastercard_approved','Mastercard','4444'],'378282246310005':['demo_amex_approved','Amex','0005']};
function emit(type,card){parent.postMessage({type:type,channel:channel,card:card},'*')}
function resize(){if(channel)parent.postMessage({type:'PMS_DEMO_RESIZE',channel:channel,height:Math.ceil(document.body.getBoundingClientRect().height)+12},'*')}
function digits(value){return value.replace(/\\D/g,'')}
function brand(value){return /^4/.test(value)?'Visa':/^5[1-5]/.test(value)?'Mastercard':/^3[47]/.test(value)?'Amex':''}
function validate(input){
var cardNumber=digits(number.value),issuer=brand(cardNumber),parts=digits(expiry.value),month=Number(parts.slice(0,2)),year=2000+Number(parts.slice(2)),now=new Date(),message='';
if(input===number&&!cards[cardNumber])message=cardNumber?'Usa un número de prueba válido: Visa/Mastercard 16 dígitos o Amex 15.':'Ingresa el número de tarjeta de prueba.';
if(input===expiry&&(parts.length!==4||month<1||month>12||year<now.getFullYear()||year===now.getFullYear()&&month<now.getMonth()+1))message='Ingresa una fecha vigente válida (MM / YY).';
if(input===code&&code.value!==(issuer==='Amex'?'1234':'123'))message=issuer==='Amex'?'Ingresa los 4 dígitos de prueba: 1234.':'Ingresa los 3 dígitos de prueba: 123.';
if(input===holder&&holder.value.trim().length<3)message='El nombre del titular debe tener al menos 3 caracteres.';
errors[input.id]=message;
input.setAttribute('aria-invalid',message?'true':'false');input.dataset.valid=message?'false':'true';document.getElementById(input.id+'-error').textContent=message?'⚠ '+message:'';
return !message;
}
window.addEventListener('message',function(event){if(event.source!==parent||!event.data||event.data.type!=='PMS_DEMO_INIT'||typeof event.data.channel!=='string')return;channel=event.data.channel;holder.value=typeof event.data.holderName==='string'?event.data.holderName:'';resize();});
number.addEventListener('input',function(){var value=digits(number.value).slice(0,16),issuer=brand(value);if(issuer==='Amex')value=value.slice(0,15);number.value=issuer==='Amex'?value.slice(0,4)+(value.length>4?' '+value.slice(4,10):'')+(value.length>10?' '+value.slice(10,15):''):value.replace(/(.{4})/g,'$1 ').trim();['Visa','Mastercard','Amex'].forEach(function(id){document.getElementById(id).className=id===issuer?'active':'';});code.maxLength=issuer==='Amex'?4:3;code.value=code.value.slice(0,code.maxLength);if(touched.code)validate(code);});
expiry.addEventListener('input',function(){var value=digits(expiry.value).slice(0,4);expiry.value=value.slice(0,2)+(value.length>=2?' / '+value.slice(2):'');});
code.addEventListener('input',function(){code.value=digits(code.value).slice(0,brand(digits(number.value))==='Amex'?4:3);});
fields.forEach(function(input){input.addEventListener('blur',function(){touched[input.id]=true;validate(input);resize();});input.addEventListener('input',function(){emit('PMS_DEMO_CHANGED');summary.textContent='';if(touched[input.id])validate(input);resize();});});
form.addEventListener('submit',function(event){event.preventDefault();var first=null;fields.forEach(function(input){touched[input.id]=true;if(!validate(input)&&!first)first=input;});if(first){summary.textContent='Revisa los campos destacados antes de continuar.';first.focus();resize();return;}var card=cards[digits(number.value)];emit('PMS_DEMO_TOKEN',{token:card[0],brand:card[1],last4:card[2],holderName:holder.value.trim()});fields.forEach(function(input){input.value='';});});
new ResizeObserver(resize).observe(form);
})();</script></body></html>`;
