/** Isolated, synthetic hosted-fields demonstration. Scripts have no network/storage access. */
export const demoCardDocument = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-pms-synthetic-fields'; style-src 'unsafe-inline'; connect-src 'none'; form-action 'none'; base-uri 'none'">
<style>*{box-sizing:border-box}body{margin:0;color:#344638;font:13px Arial,sans-serif}form{display:grid;gap:18px}label{display:block;font-size:12px;font-weight:600;margin-bottom:8px}input{width:100%;min-width:0;height:46px;padding:12px;border:1px solid #dce2d7;border-radius:9px;background:white;color:#344638;font:inherit}input:focus{outline:2px solid #6b7c62;outline-offset:2px}input[aria-invalid=true]{border-color:#db8899;background:#fff7f8}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.brands{display:flex;gap:8px;margin-top:9px}.brands span{padding:5px 8px;background:#e7ebe4;border-radius:5px;color:#747d70;font-size:10px;font-weight:bold}.brands span.active{color:#344e38;background:#d6e2d2}small{display:block;color:#6c7768;font-size:11px;line-height:1.7;margin-top:8px}button{width:100%;min-height:44px;background:#5a6b5d;color:white;border:0;border-radius:9px;font:inherit;font-weight:600;cursor:pointer}button:hover{background:#485b4c}button:focus-visible{outline:2px solid #344638;outline-offset:3px}#error{color:#a63048;line-height:1.7;margin:0;min-height:18px}@media(max-width:350px){.grid{gap:10px}}</style></head><body>
<form novalidate aria-label="Tarjeta de prueba aislada"><div><label for="number">Número de tarjeta de prueba</label><input id="number" inputmode="numeric" maxlength="23" autocomplete="off" placeholder="4242 4242 4242 4242" aria-describedby="samples error"><div class="brands" aria-label="Marcas de tarjeta"><span id="Visa">VISA</span><span id="Mastercard">Mastercard</span><span id="Amex">AMEX</span></div><small id="samples">Solo datos ficticios: Visa 4242 4242 4242 4242 · Mastercard 5555 5555 5555 4444 · Amex 3782 822463 10005. No ingreses tu tarjeta real.</small></div>
<div class="grid"><div><label for="expiry">Fecha de expiración</label><input id="expiry" inputmode="numeric" maxlength="7" autocomplete="off" placeholder="MM / YY" aria-describedby="error"></div><div><label for="code">CVC / CVV de prueba</label><input id="code" type="password" inputmode="numeric" maxlength="4" autocomplete="off" placeholder="123" aria-describedby="code-help error"><small id="code-help">Ejemplo: 123; Amex: 1234. Código del reverso (Amex: anverso).</small></div></div>
<div><label for="holder">Nombre del titular</label><input id="holder" maxlength="250" autocomplete="off" aria-describedby="error"></div><p id="error" role="alert"></p><button type="submit">Usar tarjeta de prueba</button></form>
<script nonce="pms-synthetic-fields">(function(){
var channel='';var number=document.getElementById('number'),expiry=document.getElementById('expiry'),code=document.getElementById('code'),holder=document.getElementById('holder'),error=document.getElementById('error');
function emit(type,card){parent.postMessage({type:type,channel:channel,card:card},'*')}
function brand(digits){return /^4/.test(digits)?'Visa':/^5[1-5]/.test(digits)?'Mastercard':/^3[47]/.test(digits)?'Amex':''}
window.addEventListener('message',function(event){if(event.source!==parent||!event.data||event.data.type!=='PMS_DEMO_INIT'||typeof event.data.channel!=='string')return;channel=event.data.channel;holder.value=event.data.holderName||'';});
number.addEventListener('input',function(){var digits=number.value.replace(/\\D/g,'').slice(0,19),issuer=brand(digits);number.value=issuer==='Amex'?digits.slice(0,4)+(digits.length>4?' '+digits.slice(4,10):'')+(digits.length>10?' '+digits.slice(10,15):''):digits.replace(/(.{4})/g,'$1 ').trim();['Visa','Mastercard','Amex'].forEach(function(id){document.getElementById(id).className=id===issuer?'active':'';});});
expiry.addEventListener('input',function(){var digits=expiry.value.replace(/\\D/g,'').slice(0,4);expiry.value=digits.slice(0,2)+(digits.length>2?' / '+digits.slice(2):'');});
code.addEventListener('input',function(){code.value=code.value.replace(/\\D/g,'').slice(0,4);});
document.querySelector('form').addEventListener('input',function(){emit('PMS_DEMO_CHANGED');error.textContent='';[number,expiry,code,holder].forEach(function(input){input.setAttribute('aria-invalid','false')});});
document.querySelector('form').addEventListener('submit',function(event){event.preventDefault();var digits=number.value.replace(/\\D/g,''),cards={'4242424242424242':['demo_visa_approved','Visa','4242'],'5555555555554444':['demo_mastercard_approved','Mastercard','4444'],'378282246310005':['demo_amex_approved','Amex','0005']},card=cards[digits],problem=null,message='',parts=expiry.value.replace(/\\D/g,''),month=Number(parts.slice(0,2)),year=2000+Number(parts.slice(2)),now=new Date();
if(!card){problem=number;message='Usa uno de los números ficticios indicados.'}else if(parts.length!==4||month<1||month>12||year<now.getFullYear()||year===now.getFullYear()&&month<now.getMonth()+1){problem=expiry;message='Ingresa una fecha futura válida (MM / YY).'}else if(code.value!==(card[1]==='Amex'?'1234':'123')){problem=code;message='Usa el código de prueba indicado.'}else if(!holder.value.trim()){problem=holder;message='Ingresa el nombre del titular.'}
if(problem){error.textContent=message;problem.setAttribute('aria-invalid','true');problem.focus();return}emit('PMS_DEMO_TOKEN',{token:card[0],brand:card[1],last4:card[2],holderName:holder.value.trim()});number.value='';code.value='';expiry.value='';});
})();</script></body></html>`;
