import { StyleSheet } from 'react-native';

import { tokens } from '@/shared/theme/tokens';

export const loginStyles = StyleSheet.create({
  brand: {
    color: tokens.color.brand,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  button: {
    alignItems: 'center',
    backgroundColor: tokens.color.brand,
    borderRadius: tokens.radius.control,
    height: tokens.layout.buttonHeight,
    justifyContent: 'center',
    paddingHorizontal: tokens.space.md,
  },
  buttonDisabled: { opacity: 0.55 },
  buttonLabel: {
    color: tokens.color.white,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    fontWeight: '600',
  },
  card: {
    backgroundColor: tokens.color.white,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.card,
    borderWidth: 1,
    gap: tokens.space.lg,
    padding: tokens.space.lg,
  },
  field: { gap: tokens.space.xs },
  fieldError: {
    color: tokens.color.destructive,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.bodyMedium,
  },
  input: {
    backgroundColor: tokens.color.white,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.control,
    borderWidth: 1,
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    height: tokens.layout.controlHeight,
    paddingHorizontal: tokens.space.md,
  },
  inputInvalid: { borderColor: tokens.color.destructive },
  label: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.bodyMedium,
    fontWeight: '600',
  },
  passwordControl: { position: 'relative' },
  passwordField: { gap: tokens.space.xs },
  passwordInput: { paddingRight: tokens.layout.controlHeight + tokens.space.sm },
  passwordToggle: {
    alignItems: 'center',
    borderRadius: tokens.radius.control,
    height: tokens.layout.controlHeight,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 0,
    width: tokens.layout.controlHeight,
  },
  screen: { backgroundColor: tokens.color.surface, flex: 1 },
  scroll: { flex: 1 },
  scrollContent: { flexGrow: 1, justifyContent: 'center', padding: tokens.layout.screenInset },
  secondaryAction: {
    alignItems: 'center',
    borderColor: tokens.color.brandSoft,
    borderRadius: tokens.radius.control,
    borderWidth: 1,
    minHeight: tokens.layout.buttonHeight,
    justifyContent: 'center',
    paddingHorizontal: tokens.space.md,
  },
  secondaryActionDisabled: { opacity: 0.55 },
  secondaryActionLabel: {
    color: tokens.color.brand,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    fontWeight: '600',
  },
  stateCard: {
    backgroundColor: tokens.color.surfaceMuted,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.card,
    borderWidth: 1,
    gap: tokens.space.sm,
    padding: tokens.space.md,
  },
  offlineStateCard: { backgroundColor: tokens.color.pendingSurface },
  stateBody: {
    color: tokens.color.muted,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.bodyMedium,
  },
  stateTitle: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    fontWeight: '600',
  },
  heading: { gap: tokens.space.xs },
  subtitle: {
    color: tokens.color.muted,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
  },
  title: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.title,
    fontWeight: '600',
  },
});
