import { StyleSheet } from 'react-native';

import { tokens } from '@/shared/theme/tokens';

export const valetStyles = StyleSheet.create({
  screen: {
    backgroundColor: tokens.color.surface,
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  content: {
    gap: tokens.space.md,
    padding: tokens.layout.screenInset,
    paddingBottom: tokens.space.xxl,
  },
  stateContent: {
    flexGrow: 1,
  },
  successContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  title: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.title,
    fontWeight: '600',
  },
  subtitle: {
    color: tokens.color.muted,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.bodyMedium,
  },
  card: {
    backgroundColor: tokens.color.white,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.card,
    borderWidth: 1,
    gap: tokens.space.xs,
    padding: tokens.space.md,
  },
  cardHeading: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.sectionTitle,
    fontWeight: '600',
  },
  bodyText: {
    color: tokens.color.ink,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.bodyMedium,
  },
  mutedText: {
    color: tokens.color.muted,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.body,
  },
  etaCard: {
    backgroundColor: tokens.color.surfaceAccent,
    borderColor: tokens.color.brand,
  },
  actionHeading: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    fontWeight: '600',
  },
  button: {
    alignItems: 'center',
    backgroundColor: tokens.color.brand,
    borderRadius: tokens.radius.control,
    height: tokens.layout.buttonHeight,
    justifyContent: 'center',
    paddingHorizontal: tokens.space.md,
  },
  buttonDisabled: {
    backgroundColor: tokens.color.brandSoft,
  },
  buttonLabel: {
    color: tokens.color.white,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    fontWeight: '600',
  },
  stateCard: {
    backgroundColor: tokens.color.surfaceMuted,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.card,
    borderWidth: 1,
    gap: tokens.space.sm,
    padding: tokens.space.lg,
  },
  successStateCard: {
    backgroundColor: tokens.color.surfaceAccent,
    borderColor: tokens.color.brand,
  },
  offlineStateCard: {
    backgroundColor: tokens.color.pendingSurface,
  },
  stateTitle: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.sectionTitle,
    fontWeight: '600',
  },
  stateBody: {
    color: tokens.color.muted,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.bodyMedium,
  },
  skeleton: {
    backgroundColor: tokens.color.border,
    borderRadius: tokens.radius.control,
    height: tokens.layout.controlHeight,
  },
  modalBackdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalScroll: {
    flexGrow: 1,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: tokens.color.surface,
    borderTopLeftRadius: tokens.radius.card,
    borderTopRightRadius: tokens.radius.card,
    gap: tokens.space.md,
    padding: tokens.layout.screenInset,
  },
  prefixPickerBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    flex: 1,
    justifyContent: 'center',
    padding: tokens.layout.screenInset,
  },
  prefixPickerSheet: {
    backgroundColor: tokens.color.surface,
    borderRadius: tokens.radius.card,
    gap: tokens.space.sm,
    maxHeight: 360,
    padding: tokens.space.md,
    width: '82%',
  },
  prefixPickerOptions: {
    gap: tokens.space.xs,
  },
  detailList: {
    gap: tokens.space.xs,
  },
  vehicleOption: {
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.control,
    borderWidth: 1,
    gap: tokens.space.xs,
    padding: tokens.space.sm,
  },
  vehicleOptionSelected: {
    backgroundColor: tokens.color.surfaceAccent,
    borderColor: tokens.color.brand,
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: tokens.color.brand,
    borderRadius: tokens.radius.control,
    borderWidth: 1,
    flexDirection: 'row',
    gap: tokens.space.xs,
    height: tokens.layout.buttonHeight,
    justifyContent: 'center',
    paddingHorizontal: tokens.space.md,
  },
  secondaryButtonLabel: {
    color: tokens.color.brand,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.label,
    fontWeight: '600',
  },
  inputLabel: {
    color: tokens.color.inkStrong,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.body,
    fontWeight: '600',
  },
  input: {
    backgroundColor: tokens.color.white,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.control,
    borderWidth: 1,
    color: tokens.color.ink,
    fontFamily: tokens.typography.family,
    height: tokens.layout.controlHeight,
    paddingHorizontal: tokens.space.sm,
  },
  dateTimeButton: {
    alignItems: 'center',
    backgroundColor: tokens.color.white,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.control,
    borderWidth: 1,
    height: tokens.layout.controlHeight,
    justifyContent: 'center',
    paddingHorizontal: tokens.space.sm,
  },
  stepper: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: tokens.space.md,
  },
  stepperButton: {
    alignItems: 'center',
    backgroundColor: tokens.color.surfaceAccent,
    borderRadius: tokens.radius.control,
    height: tokens.layout.buttonHeight,
    justifyContent: 'center',
    width: tokens.layout.buttonHeight,
  },
  stepperLabel: {
    color: tokens.color.brand,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.sectionTitle,
  },
  locationField: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  plateRow: { flexDirection: 'row', gap: tokens.space.sm },
  platePrefix: { alignItems: 'center', backgroundColor: tokens.color.surfaceAccent, borderColor: tokens.color.border, borderRadius: tokens.radius.control, borderWidth: 1, justifyContent: 'center', minWidth: tokens.layout.buttonHeight, paddingHorizontal: tokens.space.sm },
  locationInput: {
    backgroundColor: tokens.color.white,
    borderColor: tokens.color.border,
    borderBottomLeftRadius: tokens.radius.control,
    borderTopLeftRadius: tokens.radius.control,
    borderWidth: 1,
    color: tokens.color.ink,
    flex: 1,
    fontFamily: tokens.typography.family,
    height: tokens.layout.controlHeight,
    paddingHorizontal: tokens.space.sm,
  },
  inputInvalid: {
    borderColor: tokens.color.pendingText,
  },
  fieldError: {
    color: tokens.color.pendingText,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.caption,
  },
  locationButton: {
    alignItems: 'center',
    backgroundColor: tokens.color.surfaceAccent,
    borderColor: tokens.color.brand,
    borderBottomRightRadius: tokens.radius.control,
    borderTopRightRadius: tokens.radius.control,
    borderWidth: 1,
    height: tokens.layout.controlHeight,
    justifyContent: 'center',
    width: tokens.layout.controlHeight,
  },
  locationIcon: {
    fontSize: tokens.typography.size.sectionTitle,
  },
  validationText: {
    color: tokens.color.pendingText,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.body,
  },
  estimateCard: {
    backgroundColor: tokens.color.surfaceAccent,
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.card,
    borderWidth: 1,
    gap: tokens.space.xs,
    padding: tokens.space.md,
  },
  mapButton: {
    alignItems: 'center',
    borderColor: tokens.color.brand,
    borderRadius: tokens.radius.control,
    borderWidth: 1,
    height: tokens.layout.controlHeight,
    justifyContent: 'center',
    marginTop: tokens.space.sm,
  },
  mapButtonLabel: {
    color: tokens.color.brand,
    fontFamily: tokens.typography.family,
    fontSize: tokens.typography.size.body,
    fontWeight: '600',
  },
});
