import { StyleSheet } from 'react-native';

import { tokens } from '@/shared/theme/tokens';

export const stayHomeStyles = StyleSheet.create({
  screen: { backgroundColor: tokens.color.surface, flex: 1 },
  content: { flexGrow: 1, paddingHorizontal: tokens.layout.screenInset, paddingTop: tokens.space.xl, paddingBottom: tokens.space.xl },
  pageTitle: { color: tokens.color.ink, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.title, fontWeight: '400' },
  summary: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium, marginTop: 4 },
  stayCard: { backgroundColor: tokens.color.inkStrong, borderRadius: tokens.radius.card, marginTop: tokens.space.xxl, padding: tokens.space.xl },
  stayCardEyebrow: { color: tokens.color.white, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium, fontWeight: '500' },
  stayCardTitle: { color: tokens.color.white, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.title, fontWeight: '400', marginTop: tokens.space.sm },
  stayCardDate: { color: tokens.color.white, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium, marginTop: tokens.space.sm },
  stayStatus: { color: tokens.color.white, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.caption, marginTop: tokens.space.xs, opacity: 0.8 },
  reference: { alignSelf: 'flex-start', backgroundColor: tokens.color.brandSoft, borderRadius: tokens.radius.chip, marginTop: tokens.space.md, paddingHorizontal: tokens.space.sm, paddingVertical: tokens.space.sm },
  referenceText: { color: tokens.color.white, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium, fontWeight: '500' },
  sectionTitle: { color: tokens.color.ink, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.sectionTitle, fontWeight: '600', marginTop: tokens.space.xxl },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: tokens.space.md, marginTop: tokens.space.lg },
  actionCard: { backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderRadius: tokens.radius.card, borderWidth: 1, minHeight: 108, padding: tokens.space.md, width: '47.5%' },
  actionTitle: { color: tokens.color.ink, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label, fontWeight: '600' },
  actionDescription: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.caption, lineHeight: 16, marginTop: tokens.space.xs },
  requestCard: { backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderRadius: tokens.radius.card, borderWidth: 1, marginTop: tokens.space.xxl, padding: tokens.space.md },
  requestHeading: { color: tokens.color.ink, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium, fontWeight: '600' },
  requestRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: tokens.space.sm },
  requestTitle: { color: tokens.color.ink, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium, fontWeight: '500' },
  pendingChip: { backgroundColor: tokens.color.pendingSurface, borderRadius: tokens.radius.chip, paddingHorizontal: tokens.space.sm, paddingVertical: tokens.space.xs },
  pendingLabel: { color: tokens.color.pendingText, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.caption, fontWeight: '600' },
  state: { alignItems: 'center', flex: 1, justifyContent: 'center', padding: tokens.layout.screenInset },
  stateTitle: { color: tokens.color.ink, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.sectionTitle, fontWeight: '600' },
  stateBody: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium, marginTop: tokens.space.sm, textAlign: 'center' },
  bottomNavigation: { backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-around', paddingBottom: tokens.space.sm, paddingTop: tokens.space.sm },
  navItem: { alignItems: 'center', minWidth: 58, paddingVertical: tokens.space.xs },
  navItemActive: { backgroundColor: tokens.color.surfaceAccent, borderRadius: tokens.radius.chip },
  navLabel: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.caption },
  navLabelActive: { color: tokens.color.brand, fontWeight: '600' },
});
