export const tokens = {
  color: {
    ink: '#252925',
    inkStrong: '#292B29',
    muted: '#6B716C',
    brand: '#586456',
    brandSoft: '#7C8B78',
    surface: '#F8F7F3',
    surfaceMuted: '#F1F0EC',
    surfaceAccent: '#EDF1EA',
    border: '#E2E1DC',
    pendingSurface: '#F7ECD8',
    pendingText: '#A8732A',
    white: '#FFFFFF',
    black: '#000000',
  },
  typography: {
    family: 'Inter',
    size: {
      caption: 11,
      body: 12,
      bodyMedium: 13,
      label: 15,
      sectionTitle: 18,
      title: 26,
    },
  },
  space: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
    guestNavigationInset: 18,
  },
  radius: {
    control: 10,
    chip: 12,
    card: 16,
    guestNavigationTab: 14,
  },
  layout: {
    screenInset: 24,
    controlHeight: 48,
    buttonHeight: 44,
    guestNavigationHeight: 76,
    guestNavigationTabHeight: 52,
  },
} as const;
