import { Pressable, StyleSheet, Text, View } from 'react-native';

import { tokens } from '@/shared/theme/tokens';

export function ServiceCatalogItemCard({ title, price, quantity, disabled = false, incrementDisabled, decrementDisabled, onIncrement, onDecrement, testID }: { title: string; price?: string; quantity: number; disabled?: boolean; incrementDisabled?: boolean; decrementDisabled?: boolean; onIncrement: () => void; onDecrement: () => void; testID: string }) {
  const disableDecrement = disabled || decrementDisabled === true || quantity === 0;
  const disableIncrement = disabled || incrementDisabled === true;
  return <View style={styles.card} testID={testID}><View style={styles.copy}><Text style={styles.title}>{title}</Text>{price ? <Text style={styles.price}>{price}</Text> : null}</View><View style={styles.stepper}><Pressable accessibilityLabel={`Disminuir cantidad de ${title}`} accessibilityRole="button" accessibilityState={{ disabled: disableDecrement }} disabled={disableDecrement} onPress={onDecrement} style={styles.control} testID={`${testID}-decrement`}><Text style={styles.controlLabel}>−</Text></Pressable><Text accessibilityLabel={`Cantidad de ${title}: ${quantity}`} style={styles.quantity}>{quantity}</Text><Pressable accessibilityLabel={`Aumentar cantidad de ${title}`} accessibilityRole="button" accessibilityState={{ disabled: disableIncrement }} disabled={disableIncrement} onPress={onIncrement} style={styles.control} testID={`${testID}-increment`}><Text style={styles.controlLabel}>+</Text></Pressable></View></View>;
}

const styles = StyleSheet.create({ card: { alignItems: 'center', backgroundColor: tokens.color.white, borderColor: tokens.color.border, borderRadius: tokens.radius.card, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: tokens.layout.controlHeight * 2, padding: tokens.space.md }, copy: { flex: 1, gap: tokens.space.xs, paddingRight: tokens.space.sm }, title: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.label }, price: { color: tokens.color.muted, fontFamily: tokens.typography.family, fontSize: tokens.typography.size.bodyMedium }, stepper: { alignItems: 'center', flexDirection: 'row', gap: tokens.space.sm }, control: { alignItems: 'center', backgroundColor: tokens.color.surfaceAccent, borderRadius: tokens.radius.control, height: tokens.layout.buttonHeight, justifyContent: 'center', width: tokens.layout.buttonHeight }, controlLabel: { color: tokens.color.brand, fontSize: tokens.typography.size.sectionTitle }, quantity: { color: tokens.color.inkStrong, fontFamily: tokens.typography.family, minWidth: tokens.space.md, textAlign: 'center' } });
