import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { act, fireEvent, render, waitFor } from '@testing-library/react-native';
import { Text } from 'react-native';

import { NetworkError } from '@/data/remote/http/HttpError';
import { SessionServiceRequestsProvider, useSessionServiceRequests } from '@/modules/service-requests';
import { AMENITIES_MAX_ITEM_QUANTITY, amenitiesCatalogFixture, AmenitiesScreen, areAmenitiesRequestItemsValid, MockAmenitiesService, type AmenitiesRequest } from '@/modules/services/amenities';
import { updateAmenitiesQuantity } from '@/modules/services/amenities/presentation/AmenitiesScreen';

function Probe() { const { requests } = useSessionServiceRequests(); return <Text testID="amenities-requests">{JSON.stringify(requests)}</Text>; }
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>((done) => { resolve = done; }); return { promise, resolve }; }
async function setup(service = new MockAmenitiesService()) { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><SessionServiceRequestsProvider><Probe /><AmenitiesScreen nowMs={() => new Date(2026, 8, 11, 13, 0).getTime()} service={service} /></SessionServiceRequestsProvider></QueryClientProvider>); }
async function enterSchedule(ui: Awaited<ReturnType<typeof render>>) { await fireEvent.press(ui.getByTestId('amenities-cart-button')); await waitFor(() => expect(ui.getByTestId('amenities-next')).toBeTruthy()); await fireEvent.press(ui.getByTestId('amenities-next')); await waitFor(() => expect(ui.getByTestId('amenities-submit')).toBeTruthy()); }

describe('Amenidades — IMP-AND-0113', () => {
  it('uses exactly the approved frontend/mock catalogue without prices', () => { expect(amenitiesCatalogFixture.map((item) => item.name)).toEqual(['Toallas adicionales', 'Almohada adicional', 'Kit dental', 'Kit de aseo', 'Pantuflas']); expect(JSON.stringify(amenitiesCatalogFixture)).not.toMatch(/price|stock|sku/i); });
  it('keeps quantities between one and five, rejects invalid request items, and removes a zero line', () => { expect(updateAmenitiesQuantity([], 'extra-towels', 1)).toEqual([{ itemFixtureKey: 'extra-towels', quantity: 1 }]); expect(updateAmenitiesQuantity([{ itemFixtureKey: 'extra-towels', quantity: AMENITIES_MAX_ITEM_QUANTITY }], 'extra-towels', AMENITIES_MAX_ITEM_QUANTITY + 1)).toEqual([{ itemFixtureKey: 'extra-towels', quantity: AMENITIES_MAX_ITEM_QUANTITY }]); expect(updateAmenitiesQuantity([{ itemFixtureKey: 'extra-towels', quantity: 1 }], 'extra-towels', 0)).toEqual([]); expect(areAmenitiesRequestItemsValid([{ itemFixtureKey: 'extra-towels', quantity: AMENITIES_MAX_ITEM_QUANTITY }])).toBe(true); expect(areAmenitiesRequestItemsValid([{ itemFixtureKey: 'extra-towels', quantity: AMENITIES_MAX_ITEM_QUANTITY + 1 }])).toBe(false); });
  it('disables the Amenities increment in catalog and cart at five per line', async () => { const ui = await setup(); await waitFor(() => expect(ui.getByTestId('amenities-item-extra-towels-increment')).toBeTruthy()); for (let quantity = 0; quantity < AMENITIES_MAX_ITEM_QUANTITY; quantity += 1) await fireEvent.press(ui.getByTestId('amenities-item-extra-towels-increment')); expect(ui.getByTestId('amenities-item-extra-towels-increment').props.accessibilityState.disabled).toBe(true); await fireEvent.press(ui.getByTestId('amenities-cart-button')); expect(ui.getByTestId('amenities-cart-item-extra-towels-increment').props.accessibilityState.disabled).toBe(true); expect(ui.getByLabelText(`Cantidad de Toallas adicionales: ${AMENITIES_MAX_ITEM_QUANTITY}`)).toBeTruthy(); });
  it('separates catalog, cart notes, and scheduling with a quantity badge', async () => { const ui = await setup(); await waitFor(() => expect(ui.getByTestId('amenities-item-extra-towels')).toBeTruthy()); expect(ui.getByText('Habitación 204')).toBeTruthy(); expect(ui.queryByTestId('amenities-notes')).toBeNull(); expect(ui.queryByTestId('amenities-submit')).toBeNull(); await fireEvent.press(ui.getByTestId('amenities-item-extra-towels-increment')); expect(ui.getByTestId('amenities-cart-badge').props.children).toBe(1); await fireEvent.press(ui.getByTestId('amenities-cart-button')); expect(ui.getByTestId('amenities-notes').props.maxLength).toBe(500); expect(ui.queryByTestId('amenities-time-selector')).toBeNull(); await fireEvent.changeText(ui.getByTestId('amenities-notes'), 'Puerta entreabierta\nGracias'); await fireEvent.press(ui.getByTestId('amenities-next')); expect(ui.getByTestId('amenities-time-selector')).toBeTruthy(); expect(ui.queryByTestId('amenities-notes')).toBeNull(); await fireEvent.press(ui.getByTestId('amenities-back')); expect(ui.getByTestId('amenities-notes').props.value).toBe('Puerta entreabierta\nGracias'); });
  it('trims notes, blocks duplicate submit, and creates a session request only after success', async () => { const pending = deferred<void>(); const submitRequest = jest.fn(() => pending.promise); const ui = await setup(new MockAmenitiesService(submitRequest)); await waitFor(() => expect(ui.getByTestId('amenities-item-extra-towels-increment')).toBeTruthy()); await fireEvent.press(ui.getByTestId('amenities-item-extra-towels-increment')); await fireEvent.press(ui.getByTestId('amenities-cart-button')); await fireEvent.changeText(ui.getByTestId('amenities-notes'), '  Entregar en recepción\npor favor  '); await fireEvent.press(ui.getByTestId('amenities-next')); await waitFor(() => expect(ui.getByTestId('amenities-submit')).toBeTruthy()); await fireEvent.press(ui.getByTestId('amenities-submit')); await fireEvent.press(ui.getByTestId('amenities-submit')); await waitFor(() => expect(submitRequest).toHaveBeenCalledTimes(1)); expect(submitRequest).toHaveBeenCalledWith(expect.objectContaining({ notes: 'Entregar en recepción\npor favor', items: [{ itemFixtureKey: 'extra-towels', quantity: 1 }] })); expect(ui.getByTestId('amenities-requests').props.children).toBe('[]'); await act(async () => pending.resolve()); await waitFor(() => expect(ui.getByTestId('amenities-success')).toBeTruthy()); expect(JSON.parse(ui.getByTestId('amenities-requests').props.children)[0]).toEqual(expect.objectContaining({ kind: 'AMENITIES', title: 'Amenidades' })); });
  it('warns only when a create draft leaves the service flow and preserves it on cancel', async () => {
    const ui = await setup();
    await waitFor(() => expect(ui.getByTestId('amenities-item-extra-towels-increment')).toBeTruthy());
    await fireEvent.press(ui.getByTestId('amenities-item-extra-towels-increment'));
    await fireEvent.press(ui.getByTestId('amenities-cart-button'));
    await fireEvent.press(ui.getByTestId('amenities-back'));
    expect(ui.queryByTestId('amenities-discard-modal')).toBeNull();
    await fireEvent.press(ui.getByTestId('amenities-back'));
    expect(ui.getByTestId('amenities-discard-modal')).toBeTruthy();
    await fireEvent.press(ui.getByTestId('amenities-discard-modal-cancel'));
    expect(ui.getByTestId('amenities-cart-badge').props.children).toBe(1);
  });
  it.each(['', '   \n  '])('omits whitespace notes (%s)', async (notes) => { const submitRequest = jest.fn<Promise<void>, [AmenitiesRequest]>(async () => undefined); const ui = await setup(new MockAmenitiesService(submitRequest)); await waitFor(() => expect(ui.getByTestId('amenities-item-extra-towels-increment')).toBeTruthy()); await fireEvent.press(ui.getByTestId('amenities-item-extra-towels-increment')); await fireEvent.press(ui.getByTestId('amenities-cart-button')); await fireEvent.changeText(ui.getByTestId('amenities-notes'), notes); await fireEvent.press(ui.getByTestId('amenities-next')); await waitFor(() => expect(ui.getByTestId('amenities-submit')).toBeTruthy()); await fireEvent.press(ui.getByTestId('amenities-submit')); await waitFor(() => expect(submitRequest).toHaveBeenCalledWith(expect.not.objectContaining({ notes: expect.anything() }))); });
  it.each([['error', new Error('failure')], ['offline', new NetworkError()]])('keeps cart configuration and retries after submit %s', async (kind, error) => { const submitRequest = jest.fn<Promise<void>, [AmenitiesRequest]>().mockRejectedValueOnce(error).mockResolvedValueOnce(undefined); const ui = await setup(new MockAmenitiesService(submitRequest)); await waitFor(() => expect(ui.getByTestId('amenities-item-extra-towels-increment')).toBeTruthy()); await fireEvent.press(ui.getByTestId('amenities-item-extra-towels-increment')); await enterSchedule(ui); await fireEvent.press(ui.getByTestId('amenities-submit')); await waitFor(() => expect(ui.getByTestId(`amenities-submit-${kind}`)).toBeTruthy()); await fireEvent.press(ui.getByTestId('amenities-submit')); await waitFor(() => expect(ui.getByTestId('amenities-success')).toBeTruthy()); });
});
